---
- name: restart alertmanager
  become: true
  systemd:
    daemon_reload: true
    name: "alertmanager-{{ alertmanager_namespace }}"
    state: restarted

- name: reload alertmanager
  become: true
  systemd:
    name: "alertmanager-{{ alertmanager_namespace }}"
    state: reloaded
